compressionLevel: mixed
enableGlobalCache: false
nmHoistingLimits: none
nodeLinker: pnp

pnpUnpluggedFolder: ./.yarn/unplugged
pnpMode: loose

# packageExtensions ENABLED to fix the problem
packageExtensions:
  "my-library@*":
    dependencies:
      supports-color: "*"
